DROP DATABASE IF EXISTS trail_tales_test;
DROP DATABASE IF EXISTS trail_tales;
DROP EXTENSION IF EXISTS postgis;

CREATE DATABASE trail_tales_test;
CREATE DATABASE trail_tales;
CREATE EXTENSION postgis;
